import torch
import numpy as np

IS_TRAINING=True # this will use train data if True, otherwise test data
BATCH_SIZE = 64
SAMPLE_RATE = 22500 #22.5kHz
SAMPLE_LENGTH_SECONDS = 1
LEARNING_RATE = 1e-4
EPOCHS=20

#CONFIG DATA PREP TRANSFORM TO MEL SPECTROGRAM
WINDOW_LENGTH=1024
HOP_LENGTH=256
N_FFT=1024
N_MELS=80
FMIN=20.0
FMAX=SAMPLE_RATE/2
POWER=1.0
NORMALIZED=True

